### ISSUE TITLE
audio file upload progress with redux-saga

### ISSUE THREAD

**Issue by sujinleeme** [sujinleeme/vocal-remover-app#17]
[File Upload Progress with Redux-Saga](https://decembersoft.com/posts/file-upload-progress-with-redux-saga/)

# TODO
- [ ] Show Success/Fail message snack bar
- [ ] File Upload Process status UI
- [ ] After drag and drop a file and show snack bar message
